name:
  job_test
on: 
  push:
  workflow_distpatch:
job:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: date
  job2:
    runs-on: ubuntu-latest
    steps:
    - run: date
  job3:
  needs: [job1, job2]
  runs-on: ubuntu-latest
    steps:
    - run: date
