name:
  workflow_test

on: 
  workflow_dispatch

jobs:
  wf_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Print date
        run: |
          date
      
  wf_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wf job artifact
          path: .github/
  
